package LeetCode.Easy;

import java.util.HashMap;
import java.util.Map;

public class FindTheDifference {
//    You are given two strings s and t.
//
//    String t is generated by random shuffling string s and then add one more letter at a random position.
//
//    Return the letter that was added to t.
//
//
//
//    Example 1:
//
//    Input: s = "abcd", t = "abcde"
//    Output: "e"
//    Explanation: 'e' is the letter that was added.
//    Example 2:
//
//    Input: s = "", t = "y"
//    Output: "y"
//    Example 3:
//
//    Input: s = "a", t = "aa"
//    Output: "a"
//    Example 4:
//
//    Input: s = "ae", t = "aea"
//    Output: "a"
//
//
//    Constraints:
//
//            0 <= s.length <= 1000
//    t.length == s.length + 1
//    s and t consist of lower-case English letters.

    public char findTheDifference(String s, String t) {
        char res = t.charAt(s.length());
        //String res = "";
        char[] sToChar = s.toCharArray();
        char[] tToChar = t.toCharArray();

//        for (int i =0; i < tToChar.length; i++) {
//            if (sToChar.length == 0) {
//                res = tToChar[i];
//            }
//            for (int j = 0; j < sToChar.length; j++) {
//                if (tToChar[i] == sToChar[j]) {
//                    tToChar[i] = '\0';
//                    sToChar[j] = '\0';
//
//                }
//                res = tToChar[i];
//
//            }
//
//        }

        for (int i = 0; i < s.length(); i++) {
            res += t.charAt(i) - s.charAt(i);
        }
        return res;
    }

    public static void main(String[] args) {
        String s = "a", t = "aa";
        String s1 = "abcd", t1 = "abcde";
        String s2 = "", t2 = "y";
        String s3 = "ae", t3 = "aea";
        String s4 = "ymbgaraibkfmvocpizdydugvalagaivdbfsfbepeyccqfepzvtpyxtbadkhmwmoswrcxnargtlswqemafandgkmydtimuzvjwxvlfwlhvkrgcsithaqlcvrihrwqkpjdhgfgreqoxzfvhjzojhghfwbvpfzectwwhexthbsndovxejsntmjihchaotbgcysfdaojkjldprwyrnischrgmtvjcorypvopfmegizfkvudubnejzfqffvgdoxohuinkyygbdzmshvyqyhsozwvlhevfepdvafgkqpkmcsikfyxczcovrmwqxxbnhfzcjjcpgzjjfateajnnvlbwhyppdleahgaypxidkpwmfqwqyofwdqgxhjaxvyrzupfwesmxbjszolgwqvfiozofncbohduqgiswuiyddmwlwubetyaummenkdfptjczxemryuotrrymrfdxtrebpbjtpnuhsbnovhectpjhfhahbqrfbyxggobsweefcwxpqsspyssrmdhuelkkvyjxswjwofngpwfxvknkjviiavorwyfzlnktmfwxkvwkrwdcxjfzikdyswsuxegmhtnxjraqrdchaauazfhtklxsksbhwgjphgbasfnlwqwukprgvihntsyymdrfovaszjywuqygpvjtvlsvvqbvzsmgweiayhlubnbsitvfxawhfmfiatxvqrcwjshvovxknnxnyyfexqycrlyksderlqarqhkxyaqwlwoqcribumrqjtelhwdvaiysgjlvksrfvjlcaiwrirtkkxbwgicyhvakxgdjwnwmubkiazdjkfmotglclqndqjxethoutvjchjbkoasnnfbgrnycucfpeovruguzumgmgddqwjgdvaujhyqsqtoexmnfuluaqbxoofvotvfoiexbnprrxptchmlctzgqtkivsilwgwgvpidpvasurraqfkcmxhdapjrlrnkbklwkrvoaziznlpor"
                ,
                t4 = "qhxepbshlrhoecdaodgpousbzfcqjxulatciapuftffahhlmxbufgjuxstfjvljybfxnenlacmjqoymvamphpxnolwijwcecgwbcjhgdybfffwoygikvoecdggplfohemfypxfsvdrseyhmvkoovxhdvoavsqqbrsqrkqhbtmgwaurgisloqjixfwfvwtszcxwktkwesaxsmhsvlitegrlzkvfqoiiwxbzskzoewbkxtphapavbyvhzvgrrfriddnsrftfowhdanvhjvurhljmpxvpddxmzfgwwpkjrfgqptrmumoemhfpojnxzwlrxkcafvbhlwrapubhveattfifsmiounhqusvhywnxhwrgamgnesxmzliyzisqrwvkiyderyotxhwspqrrkeczjysfujvovsfcfouykcqyjoobfdgnlswfzjmyucaxuaslzwfnetekymrwbvponiaojdqnbmboldvvitamntwnyaeppjaohwkrisrlrgwcjqqgxeqerjrbapfzurcwxhcwzugcgnirkkrxdthtbmdqgvqxilllrsbwjhwqszrjtzyetwubdrlyakzxcveufvhqugyawvkivwonvmrgnchkzdysngqdibhkyboyftxcvvjoggecjsajbuqkjjxfvynrjsnvtfvgpgveycxidhhfauvjovmnbqgoxsafknluyimkczykwdgvqwlvvgdmufxdypwnajkncoynqticfetcdafvtqszuwfmrdggifokwmkgzuxnhncmnsstffqpqbplypapctctfhqpihavligbrutxmmygiyaklqtakdidvnvrjfteazeqmbgklrgrorudayokxptswwkcircwuhcavhdparjfkjypkyxhbgwxbkvpvrtzjaetahmxevmkhdfyidhrdeejapfbafwmdqjqszwnwzgclitdhlnkaiyldwkwwzvhyorgbysyjbxsspnjdewjxbhpsvj"
                        ;
        FindTheDifference res = new FindTheDifference();
//        System.out.println(res.findTheDifference(s, t));
//        System.out.println(res.findTheDifference(s1, t1));
//        System.out.println(res.findTheDifference(s2, t2));
//        System.out.println(res.findTheDifference(s3, t3));
        System.out.println(res.findTheDifference(s4, t4));
    }
}
